baseURL = "https://www.jamespking.com/"
languageCode = "en-gb"
title = "JPK"
# theme = "m10c"

[params]
	author = "JPK"
	description = "Computer science at University of Southampton. Prev: Zealous Digital startup/marketing consulting."
[[params.social]]
	name = "github"
	url = "https://github.com/jpking10"

[params.style]
	darkestColor = "#1d2021"
	darkColor = "#282828"
	lightColor = "#d5c4a1"
	lightestColor = "#fbf1c7"
	primaryColor = "#b8bb26"

	[taxonomies]
	  category = "categories"
	    tag = "tags"
